# Generated by Django 4.1.3 on 2022-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_alter_course_students_alter_lesson_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_teacher",
            field=models.BooleanField(),
        ),
    ]
